### ISSUE TITLE
dynamic import next.js

### ISSUE THREAD

**Issue by arastepa** [andypf/json-viewer#11]
Hello does this library work with dynamic import? I get error when using dynamic import
`Type '{ data: string; indent: number; expanded: number; theme: string; showDataTypes: boolean; showToolbar: boolean; showCopy: boolean; showSize: boolean; expandIconType: string; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'data' does not exist on type 'IntrinsicAttributes'. `

![Screenshot from 2024-09-12 20-38-03](https://github.com/user-attachments/assets/0e997263-ce64-4cd4-9fa1-606be91c0098)
![Screenshot from 2024-09-12 20-37-26](https://github.com/user-attachments/assets/de4fa4a3-486f-4331-966b-d1efd255f5cd)

**Comment by arastepa** [comment]
fixed: ` 
const JsonViewer = dynamic(
  () => import('@andypf/json-viewer/dist/esm/react/JsonViewer'),
  { ssr: false },
) as typeof import('@andypf/json-viewer/dist/esm/react/JsonViewer');
 `

**Comment by andypf** [comment]
so, it's fixed? Can I close this issue?

**Comment by arastepa** [comment]
Yes
