### ISSUE TITLE
showDetails toolbar button can be in wrong state after initialization

### ISSUE THREAD

**Issue by Toutouwai** [andypf/json-viewer#5]
It seems that the showDetails button is always in the active state by default, even when json-viewer is initialized with `show-data-types="false"` and `show-size="false"`. In that scenario the button then requires two clicks before it has the expected toggling effect.

![jv](https://github.com/andypf/json-viewer/assets/1538852/d3ee4085-002e-4a14-aebe-023b8ef97ac4)

**Comment by andypf** [comment]
Thank you for reporting this issue. I will check it and work on a fix.
