### ISSUE TITLE
Property value sometime is not fit to the div/window

### ISSUE THREAD

**Issue by kokins** [andypf/json-viewer#7]
There are some moments when is needed to place big line of letter and number, without spaces and dashes to a propery of JSON. In this case unfotunetly no break happens at all and div overflows. The option _word-break: break-all_ could easily fix that, but I dont' understand where to place it from outside of the module.  

![image](https://github.com/user-attachments/assets/1b09aca4-28dd-4995-96ea-f693daa56902)

**Comment by andypf** [comment]
fixed with #8
